### ISSUE TITLE
Error if email field is not unique

### ISSUE THREAD

**Issue by raratiru** [awesto/django-shop#651]
The [docs](http://django-shop.readthedocs.io/en/latest/reference/customer-model.html?highlight=user_email#caveat-when-using-this-alternative-user-model) quote:
> The savvy reader may have noticed that in email_auth.models.User, the email field is not declared as unique. This by the way causes Django to complain during startup with:

However, I see that this is not a warning, it is an error:

```
$./manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
email_auth.User: (auth.E003) 'User.email' must be unique because it is named as the 'USERNAME_FIELD'.
```
settings.py
```
AUTH_USER_MODEL = 'email_auth.User'
HOP_GUEST_IS_ACTIVE_USER = True
SILENCED_SYSTEM_CHECKS = ['auth.W004']
```
Shall I make it unique or did I miss a setting?

**Comment by jrief** [comment]
Thanks to your problem, I just updated the docs to:

> If this directive is ``True``, customers which declared themselves as guests, may request
> a password reset, so that they can log into their account at a later time. Then it also
> makes sense to set the ``email`` field in the User model as unique.
>
> The default is ``False``.

Therefore, since you set ``SHOP_GUEST_IS_ACTIVE_USER = True``, you can use a User model
with email as unique.

**Comment by raratiru** [comment]
It is clear now, thank you!

**Comment by raratiru** [comment]
What about if `SHOP_GUEST_IS_ACTIVE_USER = False` ? The error is still there.

**Comment by jrief** [comment]
Django-1.10 or 1.11?

**Comment by raratiru** [comment]
Django 1.11. 

I am reading the [docs](https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD), and 

> ` USERNAME_FIELD` is used as the unique identifier

This [is](https://github.com/awesto/django-shop/blob/master/email_auth/models.py#L33) the case, isn't it?

**Comment by jrief** [comment]
Currently I'm still with Django-1.10, because the CMS is not 1.11 ready (I know, it's a shame, but please blame them).

Therefore I did not yet test against this issue yet.

Maybe Django-1.11 introduced some features to handle the problem I have with semi-anonymous users – they behave like anonymous users but actually have an entity in AUTH_USER_MODEL, without a password and unable to login.

So please downgrade to 1.10 for now until this is fixed.
Or try to adopt ``email_auth`` to work with Django-1.11.

**Comment by raratiru** [comment]
Sorry, my fault. 

I am using the default implementation, so it is `Django==1.10.8` according to `pip freeze`. I went down to 1.10.0 and the error message still exists.

I commented out `# AUTH_USER_MODEL = 'email_auth.User'` and two migrations where created:

```
$ ./manage.py makemigrations
Migrations for 'email_auth':
  /home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/email_auth/migrations/0005_auto_20170913_1125.py:
    - Alter field username on user
Migrations for 'shop':
  /home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/shop/migrations/0008_auto_20170913_1125.py:
    - Alter field notify on notification
    - Alter field recipient on notification

```
However, the migration process failed as expected at:

`Applying email_auth.0001_initial...`

**Comment by jrief** [comment]
ad 1) If I try this, that migration is not created
ad 2) has been fixed in PR #652 , which is awaiting a review. I will then release 0.11.1

**Comment by raratiru** [comment]
OK, the situation gets more complicated because the migrations for `myshop` application do not get populated and when I `./manage.py runserver` I receive an error:
```

Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7facc317aae8>
Traceback (most recent call last):
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/carmen/02/etis/etis/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/home/carmen/.virtualenvs/etisd/lib/python3.4/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

I am closing the ticket and start over because something is messed up really hard!

**Comment by raratiru** [comment]
For the record, it was the `shop.middleware.MethodOverrideMiddleware'` that caused the issue and I did not correctly set the `SHOP_APP_LABEL`. 

I will start over and try to see the issues one by one -if they really exist!

**Comment by raratiru** [comment]
OK, all the issues were solved when I discarded my settings.py and tried to adopt the settings from the relevant settings.py from the example.

I did not yet manage to find why the issue of the unique field error was caused by the settings file. However, the middleware error was caused  by the name `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES`. 

Thank you, I am still working on it!

**Comment by jrief** [comment]
Something I wanted to do, but had no time yet, is a cookiecutter template for django-SHOP. This would have prevented you and other to step into the same problems.

If you want to maintain such a package, you are really welcomed and I'll give you all support I can.

**Comment by raratiru** [comment]
Indeed, that would be a great booster.

I need sometime to find my way around and try to tidy up the mess I created in the settings.py.

**Comment by raratiru** [comment]
OK, I found it.

The docs need to make clear that in the `TEMPLATES > OPTIONS > context_processors`, the `'cms.context_processors.cms_settings',` must be included!

**Comment by raratiru** [comment]
I just started to realize the base idea of django-shop.

This setting, that took me the whole day to find it out, brought me in the world of django-cms and I am just starting this trip, it is exciting and it has great views!
